(in-package :mgl-pax-test)

(defparameter *clhs-body-files*
  '("00_" "01_aa" "01_ab" "01_a" "01_b" "01_c"
    "01_daa" "01_daba" "01_dabb" "01_dabc" "01_dab" "01_dac"
    "01_dada" "01_dadb" "01_dadc" "01_dadd" "01_dad" "01_dae"
    "01_daf" "01_da" "01_db" "01_dc" "01_dda" "01_ddb"
    "01_ddc" "01_ddd" "01_dde" "01_ddfa" "01_ddfb" "01_ddfc"
    "01_ddfd" "01_ddf" "01_ddg" "01_ddh" "01_dd" "01_ddi"
    "01_ddj" "01_ddk" "01_ddl" "01_ddm" "01_ddn" "01_ddo"
    "01_ddp" "01_ddq" "01_ddr" "01_dds" "01_ddta" "01_ddtb"
    "01_ddtc" "01_ddtda" "01_ddtdb" "01_ddtd" "01_ddt" "01_ddu"
    "01_ddv" "01_d" "01_eaa" "01_eab" "01_eac" "01_eadaa"
    "01_eada" "01_ead" "01_eae" "01_ea" "01_ebaa" "01_eba"
    "01_ebb" "01_eb" "01_e" "01_f" "01_g" "01_ha"
    "01_hb" "01_hc" "01_hd" "01_h" "01_" "01_i"
    "02_aaa" "02_aab" "02_aac" "02_aa" "02_ab" "02_ac"
    "02_ada" "02_adb" "02_adc" "02_add" "02_adea" "02_ade"
    "02_adfa" "02_adf" "02_adga" "02_adg" "02_ad" "02_a"
    "02_b" "02_caaa" "02_caab" "02_caa" "02_ca" "02_cbaa"
    "02_cbab" "02_cba" "02_cbb" "02_cbc" "02_cb" "02_cc"
    "02_cd" "02_ce" "02_cf" "02_c" "02_da" "02_db"
    "02_dca" "02_dc" "02_dda" "02_ddba" "02_ddbb" "02_ddbc"
    "02_ddbd" "02_ddbe" "02_ddb" "02_dd" "02_de" "02_dfa"
    "02_df" "02_dg" "02_dha" "02_dhb" "02_dhc" "02_dhda"
    "02_dhd" "02_dhe" "02_dhf" "02_dhg" "02_dhh" "02_dh"
    "02_dhi" "02_dhj" "02_dhk" "02_dhl" "02_dhm" "02_dhn"
    "02_dho" "02_dhp" "02_dhq" "02_dhr" "02_dhsa" "02_dhsb"
    "02_dhs" "02_dht" "02_d" "02_dhu" "02_dhv" "02_di"
    "02_" "03_aaa" "03_aab" "03_aaca" "03_aac" "03_aad"
    "03_aa" "03_abaaa" "03_abaab" "03_abaac" "03_abaad" "03_abaa"
    "03_ababa" "03_ababb" "03_ababc" "03_ababd" "03_abab" "03_abaca"
    "03_abac" "03_aba" "03_ab" "03_ac" "03_ad" "03_ae"
    "03_af" "03_ag" "03_a" "03_ba" "03_bbaa" "03_bbab"
    "03_bbaca" "03_bbac" "03_bba" "03_bbb" "03_bbc" "03_bb"
    "03_bcaa" "03_bcab" "03_bca" "03_bc" "03_bda" "03_bdba"
    "03_bdbb" "03_bdb" "03_bdc" "03_bdd" "03_bd" "03_be"
    "03_b" "03_ca" "03_cb" "03_cca" "03_cc" "03_cda"
    "03_cd" "03_c" "03_daa" "03_dab" "03_dac" "03_dadaa"
    "03_dada" "03_dad" "03_dae" "03_daf" "03_da" "03_db"
    "03_dc" "03_ddaaa" "03_ddaa" "03_ddab" "03_dda" "03_dd"
    "03_de" "03_df" "03_dg" "03_dh" "03_d" "03_di"
    "03_dj" "03_dk" "03_eaaa" "03_eaa" "03_eab" "03_eac"
    "03_ead" "03_eae" "03_eaf" "03_eag" "03_eah" "03_ea"
    "03_e" "03_f" "03_ga" "03_gba" "03_gb" "03_g"
    "03_" "04_a" "04_ba" "04_bb" "04_bc" "04_b"
    "04_caa" "04_ca" "04_cb" "04_cc" "04_cda" "04_cdb"
    "04_cd" "04_cea" "04_ceb" "04_ce" "04_cfa" "04_cfb"
    "04_cfc" "04_cf" "04_cg" "04_c" "04_" "05_aaaa"
    "05_aaa" "05_aaba" "05_aab" "05_aa" "05_aba" "05_abb"
    "05_abc" "05_abd" "05_abe" "05_abf" "05_abg" "05_abh"
    "05_ab" "05_abi" "05_ac" "05_a" "05_b" "05_"
    "06_aaaa" "06_aaab" "06_aaa" "06_aab" "06_aac" "06_aad"
    "06_aaea" "06_aaeb" "06_aaec" "06_aaed" "06_aaee" "06_aaef"
    "06_aae" "06_aaf" "06_aag" "06_aah" "06_aa" "06_abaaa"
    "06_abaa" "06_ababa" "06_abab" "06_abaca" "06_abac" "06_abada"
    "06_abad" "06_abaea" "06_abae" "06_abaf" "06_abaga" "06_abag"
    "06_aba" "06_abba" "06_abb" "06_ab" "06_aca" "06_acb"
    "06_acc" "06_acd" "06_ace" "06_ac" "06_ada" "06_adb"
    "06_adc" "06_ad" "06_aea" "06_ae" "06_afa" "06_af"
    "06_agaa" "06_aga" "06_agb" "06_ag" "06_aha" "06_ah"
    "06_a" "06_ai" "06_" "07_aa" "07_ab" "07_ac"
    "07_ad" "07_ae" "07_af" "07_ag" "07_a" "07_ba"
    "07_bb" "07_bc" "07_b" "07_ca" "07_c" "07_da"
    "07_d" "07_ea" "07_eb" "07_ec" "07_e" "07_fa"
    "07_fb" "07_fc" "07_fd" "07_fea" "07_fe" "07_ffaa"
    "07_ffab" "07_ffac" "07_ffa" "07_ffb" "07_ffc" "07_ffd"
    "07_ff" "07_fg" "07_f" "07_" "08_" "09_aaa"
    "09_aa" "09_aba" "09_ab" "09_acaa" "09_acab" "09_acac"
    "09_acad" "09_acae" "09_aca" "09_ac" "09_adaa" "09_ada"
    "09_adba" "09_adbb" "09_adbc" "09_adbd" "09_adb" "09_ad"
    "09_ae" "09_af" "09_a" "09_" "10_a" "10_"
    "11_aaa" "11_aaba" "11_aabb" "11_aabc" "11_aabd" "11_aabe"
    "11_aab" "11_aa" "11_abaa" "11_ababa" "11_abab" "11_aba"
    "11_abb" "11_abca" "11_abcb" "11_abc" "11_abd" "11_ab"
    "11_a" "11_" "12_aaaa" "12_aaa" "12_aab" "12_aaca"
    "12_aacb" "12_aac" "12_aa" "12_ab" "12_aca" "12_acb"
    "12_acc" "12_ac" "12_adaa" "12_ada" "12_adb" "12_adc"
    "12_add" "12_ad" "12_aea" "12_aeb" "12_aeca" "12_aec"
    "12_aed" "12_ae" "12_af" "12_ag" "12_a" "12_"
    "13_aa" "13_aba" "13_abb" "13_ab" "13_ac" "13_ada"
    "13_adb" "13_adca" "13_adcb" "13_adcc" "13_adcd" "13_adc"
    "13_add" "13_ade" "13_adf" "13_ad" "13_ae" "13_af"
    "13_ag" "13_ah" "13_a" "13_ai" "13_aj" "13_"
    "14_aaa" "14_aa" "14_aba" "14_abb" "14_abc" "14_ab"
    "14_a" "14_" "15_aaa" "15_aaba" "15_aab" "15_aacaa"
    "15_aaca" "15_aacba" "15_aacbb" "15_aacb" "15_aac" "15_aa"
    "15_aba" "15_abb" "15_ab" "15_a" "15_" "16_aa"
    "16_ab" "16_a" "16_" "17_aa" "17_a" "17_baa"
    "17_ba" "17_bba" "17_bb" "17_b" "17_" "18_aa"
    "18_aba" "18_abba" "18_abbb" "18_abb" "18_abca" "18_abcb"
    "18_abcc" "18_abc" "18_abd" "18_ab" "18_a" "18_"
    "19_aa" "19_ab" "19_ac" "19_a" "19_baa" "19_bab"
    "19_bac" "19_bad" "19_bae" "19_baf" "19_ba" "19_bbaa"
    "19_bbaba" "19_bbabb" "19_bbab" "19_bba" "19_bbba" "19_bbbb"
    "19_bbbca" "19_bbbc" "19_bbb" "19_bbc" "19_bbda" "19_bbdb"
    "19_bbdca" "19_bbdc" "19_bbdd" "19_bbde" "19_bbdf" "19_bbdg"
    "19_bbd" "19_bbe" "19_bb" "19_bca" "19_bc" "19_b"
    "19_caaa" "19_caab" "19_caac" "19_caad" "19_caae" "19_caaf"
    "19_caag" "19_caah" "19_caa" "19_ca" "19_cba" "19_cbb"
    "19_cb" "19_c" "19_" "20_aa" "20_ab" "20_aca"
    "20_ac" "20_a" "20_" "21_aaaa" "21_aaab" "21_aaac"
    "21_aaa" "21_aaba" "21_aab" "21_aac" "21_aa" "21_ab"
    "21_ac" "21_ad" "21_a" "21_" "22_aaaa" "22_aaa"
    "22_aa" "22_ab" "22_acaa" "22_acab" "22_acac" "22_acad"
    "22_acae" "22_aca" "22_acb" "22_acca" "22_accba" "22_accb"
    "22_acc" "22_acd" "22_ace" "22_acf" "22_acg" "22_ach"
    "22_ac" "22_aci" "22_acj" "22_ack" "22_acl" "22_acm"
    "22_ad" "22_a" "22_baa" "22_bab" "22_bac" "22_bad"
    "22_bae" "22_ba" "22_bb" "22_bc" "22_b" "22_caa"
    "22_cab" "22_cac" "22_cad" "22_cae" "22_ca" "22_cba"
    "22_cbb" "22_cbc" "22_cbd" "22_cbe" "22_cb" "22_cca"
    "22_ccb" "22_ccc" "22_ccd" "22_cc" "22_cda" "22_cdb"
    "22_cdc" "22_cd" "22_cea" "22_ceb" "22_cec" "22_ced"
    "22_ce" "22_cfa" "22_cfb" "22_cfc" "22_cf" "22_cga"
    "22_cgb" "22_cgc" "22_cgd" "22_cge" "22_cgf" "22_cg"
    "22_cha" "22_chb" "22_chc" "22_ch" "22_c" "22_cia"
    "22_cib" "22_cic" "22_ci" "22_cja" "22_cjb" "22_cjc"
    "22_cjd" "22_cj" "22_ck" "22_cl" "22_" "23_aa"
    "23_aba" "23_ab" "23_aca" "23_acb" "23_ac" "23_a"
    "23_" "24_aa" "24_abaa" "24_aba" "24_ab" "24_a"
    "24_" "25_aa" "25_ab" "25_ac" "25_ada" "25_adb"
    "25_adc" "25_add" "25_ad" "25_a" "25_" "26_a"
    "26_glo_9" "26_glo_a" "26_glo_b" "26_glo_c" "26_glo_d" "26_glo_e"
    "26_glo_f" "26_glo_g" "26_glo_h" "26_glo_i" "26_glo_k" "26_glo_l"
    "26_glo_m" "26_glo_n" "26_glo_o" "26_glo_p" "26_glo_q" "26_glo_r"
    "26_glo_s" "26_glo_t" "26_glo_u" "26_glo_v" "26_glo_w" "26_glo_y"
    "26_" "27_aa" "27_ab" "27_ac" "27_ad" "27_ae"
    "27_af" "27_ag" "27_a" "27_" "a_abort" "a_and"
    "a_atom" "a_bit" "a_ch" "a_comple" "a_cons" "a_contin"
    "a_eql" "a_error" "a_float" "a_fn" "a__" "a_lambda"
    "a_list" "a_logica" "a_member" "a_method" "a_mod" "a_muffle"
    "a_nil" "a_not" "a_null" "a_or" "a_pl" "a_pn"
    "a_ration" "a_setf" "a_sl" "a_st" "a_store_" "a_string"
    "a_t" "a_type" "a_use_va" "a_values" "a_vector" "c_arrays"
    "c_charac" "c_condit" "c_conses" "c_data_a" "c_enviro" "c_evalua"
    "c_filena" "c_files" "c_hash_t" "c_iterat" "c_number" "c_object"
    "c_packag" "c_printe" "c_reader" "c_sequen" "c_stream" "c_string"
    "c_struct" "c_symbol" "c_system" "c_types_" "d_declar" "d_dynami"
    "d_ftype" "d_ignore" "d_inline" "d_optimi" "d_specia" "d_type"
    "e_arithm" "e_cell_e" "e_cnd" "e_contro" "e_divisi" "e_end_of"
    "e_error" "e_file_e" "e_floa_1" "e_floa_2" "e_floa_3" "e_floati"
    "e_parse_" "e_pkg_er" "e_pr_not" "e_progra" "e_rder_e" "e_seriou"
    "e_smp_cn" "e_smp_er" "e_smp_tp" "e_smp_wa" "e_stm_er" "e_storag"
    "e_style_" "e_tp_err" "e_unbo_1" "e_unboun" "e_undefi" "e_warnin"
    "f_1pl_1_" "f_abortc" "f_abs" "f_acons" "f_add_me" "f_adjoin"
    "f_adju_1" "f_adjust" "f_alloca" "f_alpha_" "f_alphan" "f_append"
    "f_apply" "f_apropo" "f_ar_d_1" "f_ar_dim" "f_ar_dis" "f_aref"
    "f_ar_ele" "f_ar_has" "f_ar_in_" "f_arithm" "f_ar_ran" "f_arrayp"
    "f_ar_row" "f_ar_tot" "f_ash" "f_asin_" "f_assocc" "f_atom"
    "f_boole" "f_boundp" "f_break" "f_broadc" "f_bt_and" "f_bt_sb"
    "f_bt_vec" "f_butlas" "f_by_by" "f_call_n" "f_car_c" "f_cell_e"
    "f_cerror" "f_char_c" "f_chareq" "f_char_" "f_char_i" "f_char_n"
    "f_char_u" "f_chg_cl" "f_ch" "f_chp" "f_cis" "f_clas_1"
    "f_class_" "f_clear_" "f_close" "f_clrhas" "f_cmp__1" "f_cmpd_f"
    "f_cmp_fi" "f_cmp" "f_cmp_ma" "f_code_c" "f_coerce" "f_comp_1"
    "f_comp_2" "f_comp_3" "f_comple" "f_comput" "f_conc_1" "f_concat"
    "f_conjug" "f_cons_1" "f_cons" "f_consp" "f_consta" "f_countc"
    "f_cp_ali" "f_cp_lis" "f_cp_ppr" "f_cp_rdt" "f_cp_seq" "f_cp_stu"
    "f_cp_sym" "f_cp_tre" "f_dec_fl" "f_dec_un" "f_del_fi" "f_del_pk"
    "f_deposi" "f_desc_1" "f_descri" "f_digi_1" "f_digit_" "f_dir"
    "f_disass" "f_docume" "f_dpb" "f_dribbl" "f_echo_s" "f_ed"
    "f_elt" "f_encode" "f_endp" "f_ensu_1" "f_ensure" "f_eq"
    "f_eql" "f_eq_sle" "f_equal" "f_equalp" "f_error" "f_eval"
    "f_evenpc" "f_everyc" "f_exp_e" "f_export" "f_fbound" "f_fdefin"
    "f_file_a" "f_file_e" "f_file_l" "f_file_p" "f_file_s" "f_file_w"
    "f_fill" "f_fill_p" "f_find_a" "f_find_c" "f_find_" "f_find_m"
    "f_find_p" "f_find_r" "f_find_s" "f_finish" "f_firstc" "f_float"
    "f_floatp" "f_floorc" "f_fmakun" "f_fn_kwd" "f_fn_lam" "f_fnp"
    "f_format" "f_funcal" "f_gcd" "f_gensym" "f_gentem" "f_get__1"
    "f_getf" "f_gethas" "f_get" "f_get_in" "f_get_ou" "f_get_pr"
    "f_get_se" "f_get_un" "f_graphi" "f_hash_1" "f_hash_2" "f_hash_3"
    "f_hash_4" "f_hash_5" "f_hash_t" "f__" "f_identi" "f_import"
    "f_init_i" "f_inspec" "f_in_stm" "f_inte_1" "f_intege" "f_intera"
    "f_intern" "f_invali" "f_invo_1" "f_invo_2" "f_invoke" "f_isec_"
    "f_kwdp" "f_last" "f_lcm" "f_ldb" "f_ldb_te" "f_ldiffc"
    "f_ld_log" "f_length" "f_lisp_i" "f_list_a" "f_listen" "f_list_"
    "f_list_l" "f_listp" "f_load" "f_logand" "f_logbtp" "f_logcou"
    "f_log" "f_logi_1" "f_logica" "f_logtes" "f_mach_i" "f_mach_t"
    "f_mach_v" "f_macro_" "f_makunb" "f_mapc_" "f_maphas" "f_map"
    "f_map_in" "f_mask_f" "f_max_m" "f_mem_m" "f_merge" "f_merge_"
    "f_meth_1" "f_method" "f_mexp_" "f_minusp" "f_mismat" "f_mk_ar"
    "f_mk_bro" "f_mk_cnd" "f_mk_con" "f_mk_dis" "f_mk_ech" "f_mk_has"
    "f_mk_i_1" "f_mk_ins" "f_mk_l_1" "f_mk_ld_" "f_mk_lis" "f_mk_pkg"
    "f_mk_pn" "f_mk_rnd" "f_mk_s_1" "f_mk_s_2" "f_mk_seq" "f_mk_stg"
    "f_mk_sym" "f_mk_syn" "f_mk_two" "f_mod_r" "f_name_c" "f_namest"
    "f_nconc" "f_next_m" "f_no_app" "f_no_nex" "f_not" "f_nthcdr"
    "f_nth" "f_null" "f_numera" "f_nump" "f_open" "f_open_s"
    "f_opsetf" "f_pairli" "f_pars_1" "f_parse_" "f_peek_c" "f_phase"
    "f_pkg__1" "f_pkg_er" "f_pkg_na" "f_pkg_ni" "f_pkgp" "f_pkg_sh"
    "f_pkg_us" "f_pl" "f_pn_hos" "f_pn" "f_pn_mat" "f_pnp"
    "f_pos_p" "f_ppr_di" "f_ppr_fi" "f_ppr_in" "f_ppr_nl" "f_ppr_ta"
    "f_pr_not" "f_probe_" "f_pr_obj" "f_procla" "f_provid" "f_random"
    "f_rassoc" "f_rati_1" "f_ration" "f_rd_by" "f_rd_c_1" "f_rd_cha"
    "f_rd_del" "f_rd_fro" "f_rd_lin" "f_rd_rd" "f_rd_seq" "f_rdta_1"
    "f_rdtabl" "f_realpa" "f_realp" "f_reduce" "f_reinit" "f_remhas"
    "f_rempro" "f_replac" "f_rest" "f_revapp" "f_revers" "f_rm_dup"
    "f_rm_met" "f_rm_rm" "f_rnd_st" "f_rn_fil" "f_rn_pkg" "f_room"
    "f_row_ma" "f_rplaca" "f_rst_na" "f_sbs_s" "f_search" "f_set__1"
    "f_set_di" "f_set_ex" "f_set" "f_set_ma" "f_set_pp" "f_set_sy"
    "f_shadow" "f_shared" "f_shdw_i" "f_short_" "f_signal" "f_signum"
    "f_sin_c" "f_sinh_" "f_sleep" "f_sl" "f_slt_bo" "f_slt_ex"
    "f_slt_ma" "f_slt_mi" "f_slt_un" "f_slt_va" "f_smp_bt" "f_smp_cn"
    "f_smp_st" "f_smp_ve" "f_sort_" "f_specia" "f_sqrt_" "f_std_ch"
    "f_stgeq_" "f_stgp" "f_stg_tr" "f_stg_up" "f_st" "f_stm_el"
    "f_stm_er" "f_stm_ex" "f_stmp" "f_string" "f_sublis" "f_subseq"
    "f_subset" "f_substc" "f_subtpp" "f_svref" "f_sw_tpc" "f_sxhash"
    "f_symb_1" "f_symb_2" "f_symb_3" "f_symb_4" "f_symb_5" "f_symbol"
    "f_syn_st" "f_terpri" "f_tn" "f_tp_err" "f_tp_of" "f_tree_e"
    "f_tr_log" "f_tr_pn" "f_two_wa" "f_typep" "f_unboun" "f_unexpo"
    "f_uninte" "f_unionc" "f_unrd_c" "f_unuse_" "f_upda_1" "f_update"
    "f_upgr_1" "f_upgrad" "f_upper_" "f_use_pk" "f_user_h" "f_vals_l"
    "f_values" "f_vecp" "f_vec_po" "f_vec_ps" "f_vector" "f_warn"
    "f_wild_p" "f_wr_by" "f_wr_cha" "f_wr_pr" "f_wr_seq" "f_wr_stg"
    "f_wr_to_" "f_y_or_n" "f_zerop" "h_glossa" "m_and" "m_assert"
    "m_call_m" "m_case_" "m_check_" "m_cond" "m_declai" "m_defcla"
    "m_defcon" "m_defgen" "m_defi_1" "m_defi_2" "m_defi_3" "m_defi_4"
    "m_defi_5" "m_define" "m_defmac" "m_defmet" "m_defpar" "m_defpkg"
    "m_defset" "m_defstr" "m_deftp" "m_defun" "m_destru" "m_do_do"
    "m_dolist" "m_do_sym" "m_dotime" "m_format" "m_hand_1" "m_handle"
    "m_ignore" "m_incf_" "m_in_pkg" "m_lambda" "m_loop_f" "m_loop"
    "m_mult_1" "m_mult_2" "m_multip" "m_nth_va" "m_or" "m_pop"
    "m_ppr_ex" "m_ppr_lo" "m_ppr_po" "m_prog1c" "m_prog_" "m_pr_unr"
    "m_psetq" "m_pshnew" "m_push" "m_remf" "m_return" "m_rotate"
    "m_rst_bi" "m_rst_ca" "m_setf_" "m_shiftf" "m_step" "m_time"
    "m_tpcase" "m_tracec" "m_w_acce" "m_w_cnd_" "m_w_comp" "m_w_hash"
    "m_when_" "m_w_in_f" "m_w_op_1" "m_w_open" "m_w_out_" "m_w_pkg_"
    "m_w_slts" "m_w_smp_" "m_w_std_" "r_abort" "r_contin" "r_muffle"
    "r_store_" "r_use_va" "s_block" "s_catch" "s_declar" "s_eval_w"
    "s_flet_" "s_fn" "s_go" "s_if" "s_lambda" "s_ld_tim"
    "s_let_l" "s_locall" "s_mult_1" "s_multip" "s_progn" "s_progv"
    "s_quote" "s_ret_fr" "s_setq" "s_symbol" "s_tagbod" "s_the"
    "s_throw" "s_unwind" "t_and" "t_array" "t_atom" "t_ban"
    "t_base_c" "t_base_s" "t_bignum" "t_bit" "t_broadc" "t_bt_vec"
    "t_built_" "t_ch" "t_class" "t_cmpd_f" "t_comple" "t_concat"
    "t_cons" "t_echo_s" "t_eql" "t_extend" "t_file_s" "t_fixnum"
    "t_float" "t_fn" "t_generi" "t_hash_t" "t_intege" "t_kwd"
    "t_list" "t_logica" "t_member" "t_meth_1" "t_method" "t_mod"
    "t_nil" "t_not" "t_null" "t_number" "t_or" "t_pkg"
    "t_pn" "t_ratio" "t_ration" "t_rdtabl" "t_real" "t_rnd_st"
    "t_rst" "t_satisf" "t_seq" "t_sgn_by" "t_short_" "t_smp_ar"
    "t_smp_ba" "t_smp_bt" "t_smp_st" "t_smp_ve" "t_std_ch" "t_std_cl"
    "t_std_ge" "t_std_me" "t_std_ob" "t_stg_st" "t_stream" "t_string"
    "t_stu_cl" "t_stu_ob" "t_symbol" "t_syn_st" "t_t" "t_two_wa"
    "t_unsgn_" "t_values" "t_vector" "v_ar_dim" "v_ar_ran" "v_ar_tot"
    "v_b_1_b" "v_break_" "v_call_a" "v_char_c" "v_cmp_fi" "v_cmp_pr"
    "v_debugg" "v_debug_" "v_defaul" "v_featur" "v_gensym" "v__"
    "v_intern" "v_lamb_1" "v_lambda" "v_ld_pns" "v_ld_prs" "v_mexp_h"
    "v_module" "v_most_1" "v_most_p" "v_multip" "v_nil" "v_pi"
    "v_pkg" "v_pl_plp" "v_pr_ar" "v_pr_bas" "v_pr_cas" "v_pr_cir"
    "v_pr_esc" "v_pr_gen" "v_pr_lev" "v_pr_lin" "v_pr_mis" "v_pr_ppr"
    "v_pr_pre" "v_pr_rda" "v_pr_rig" "v_rd_bas" "v_rd_def" "v_rd_eva"
    "v_rd_sup" "v_rdtabl" "v_rnd_st" "v_short_" "v_sl_sls" "v__stst_"
    "v_termin" "v_t"))

(defparameter *files-with-definitions*
  (remove-duplicates
   (append (remove-if-not #'stringp
                          (mapcar #'third pax::*hyperspec-definitions*))
           (mapcar #'first pax::*hyperspec-sections*))
   :test #'equal))

(deftest test-hyperspec ()
  ;; Check that all each file under "Body/" has at least one section
  ;; or definition associated with it. The "26_glo_?" pages use
  ;; another mechanism. That leaves only the disambiguation pages
  ;; (e.g. "a_cons.htm") and "h_glossary.htm".
  (is (equal
       (sort (set-difference *clhs-body-files* *files-with-definitions*
                             :test #'string=)
             #'string<)
       '("26_glo_9" "26_glo_a" "26_glo_b" "26_glo_c" "26_glo_d" "26_glo_e"
         "26_glo_f" "26_glo_g" "26_glo_h" "26_glo_i" "26_glo_k" "26_glo_l"
         "26_glo_m" "26_glo_n" "26_glo_o" "26_glo_p" "26_glo_q" "26_glo_r"
         "26_glo_s" "26_glo_t" "26_glo_u" "26_glo_v" "26_glo_w" "26_glo_y"
         "a__" "a_abort" "a_and" "a_atom" "a_bit" "a_ch" "a_comple" "a_cons"
         "a_contin" "a_eql" "a_error" "a_float" "a_fn" "a_lambda" "a_list"
         "a_logica" "a_member" "a_method" "a_mod" "a_muffle" "a_nil" "a_not"
         "a_null" "a_or" "a_pl" "a_pn" "a_ration" "a_setf" "a_sl" "a_st"
         "a_store_" "a_string" "a_t" "a_type" "a_use_va" "a_values"
         "a_vector" "h_glossa")))
  (is (endp (set-difference *files-with-definitions* *clhs-body-files*
                            :test #'string=))))
