#+SEQ_TODO: TODO(t@) NEXT(n@) STARTED(s@) WAITING(w@) | DONE(d@) OLD(o@) CANCELLED(c@)
#+TODO: MAYBE(m@) FAILED(f@) LOG(l@) DEFERRED(e@)
* MAYBE add locatives for sbcl internals
deftransform, defoptimizer, define-vop, define-source-transfrom
* TODO export documentation generation utilities for extensions
* OPT esrap is slow with allegro cl
* OPT parse and print markdown once when *format* is :html?
This would involve rewriting everything to emit parse tree fragments.
* MAYBE todo/comment locative?
* defining link ids doesn't work in function docstrings
because it's translated to a list item
* MAYBE pretty print lambda-lists (including default values)
and values of variables. Unfortunately, there seems to be no way to
use the lisp pretty printer for this because output also includes
markup.
* MAYBE transcribe: emacs retranscribe should not update if consistent?
This either relies on the global value of
*TRANSCRIBE-CHECK-CONSISTENCY* or it needs to see the
"```cl-transcript (...)" line.
* MAYBE support external links
There are two kinds:
- object is text (like the CLHS locative)
- normal references with external urls (hyperspec symbol lookup)

The first kind is needs no additional support from pax as markdown
reference links or user defined locatives can take care of this case.

The second kind is very easy to implement: it only needs a small
change in INITIALIZE-LINKS.
* MAYBE link to MOP
* warn on linking failure
How to recoginize normal reference links? Don't, just warn on any
linking failure. This should be in 3BMD.
* MAYBE consider CommonDoc from the 40ants fork
* MAYBE split transcription off into a separate library?
* MAYBE allow lowercase only in the last "word" of the name
* MAYBE remove some markup in :PLAIN format?
* MAYBE allow markdown in titles?
* add symbol as an alias for dislocated?
* add source locative
That is, link to github, without documenting anything. Useful for code
examples without actually INCLUDEing them.
* reorder source definitions
* autoinclude docstrings
(with-implementation
  (defvar *document-uppercase-is-code* t
    "First line.")
  (defun foo ()
    "Second line.")
  "3rd line with narrative"
  (defvar saf
    "more"))

expands to

(defvar *document-uppercase-is-code* t
  "First line"
  "[foo function][docstring]"
  "3rd line with narrative"
  "more")

(defun foo ()
  "Second line.")

(defvar saf
  "more")
* MAYBE desuffix all lowercase suffixes?
* MAYBE get variable initforms from source?
Or fall back on this for deficient ARGLISTs. Will be really slow.
* test navigation from the emacs side
* create mgl-pax/minimal?
