#+SEQ_TODO: TODO(t@) NEXT(n@) STARTED(s@) WAITING(w@) | DONE(d@) OLD(o@) CANCELLED(c@)
#+TODO: MAYBE(m@) FAILED(f@) LOG(l@) DEFERRED(e@)
* MAYBE add locatives for sbcl deftransform, defoptimizer, define-vop, define-source-transfrom
* TODO export documentation generation utilities for extensions
* OPT esrap is slow with allegro cl
* MAYBE todo/comment locative?
* defining link ids doesn't work in function docstrings
because it's translated to a list item
* TODO pretty print lambda-lists (including default values)
and values of variables. Unfortunately, there seems to be no way to
use the lisp pretty printer for this because output also includes
markup.
* MAYBE include signalled errors in transcript?
What about debugger commands?
* MAYBE transcribe: add inline commands that can change prefixes and such
* MAYBE transcribe: special comment syntax for the 'narrative'
to produce something like an ipython notebook.
* MAYBE support external links
There are two kinds:
- object is text (like the CLHS locative)
- normal references with external urls (hyperspec symbol lookup)

The first kind is needs no additional support from pax as markdown
reference links or user defined locatives can take care of this case.

The second kind is very easy to implement: it only needs a small
change in INITIALIZE-LINKS.
* MAYBE link to MOP
* warn on linking failure
How to recoginize normal reference links? Don't, just warn on any
linking failure. This should be in 3BMD.
* break test-document into smaller tests
