(cl:defpackage :mgl-pax
  (:documentation "See MGL-PAX:@PAX-MANUAL.")
  (:use #:common-lisp)
  ;; These exports are redundant since PAX-BASICS exports the same
  ;; symbols, but since we cannot use MGL-PAX:DEFINE-PACKAGE to define
  ;; the package, these make sure that SBCL doesn't signal
  ;; SB-KERNEL::PACKAGE-AT-VARIANCE.
  (:export
   #:@pax-manual
   #:@pax-tutorial
   #:@pax-background
   #:@pax-emacs-integration
   #:@pax-basics
   #:@pax-markdown-support
   #:@pax-markdown-indentation
   #:@pax-markdown-syntax-highlighting
   #:@pax-documentation-printer-variables
   #:@pax-markdown-support
   #:@pax-locative-types
   #:@pax-extension-api
   #:@pax-locatives-and-references
   #:@pax-new-object-types
   #:@pax-reference-based-extensions
   #:@pax-sections
   #:define-locative-type
   #:locative
   #:variable
   #:constant
   #:accessor
   #:structure-accessor
   #:document
   #:make-reference
   #:reference-locative
   #:resolve
   #:locate
   #:locate-error
   #:locate-error-message
   #:locate-error-object
   #:locate-error-locative
   #:locate-object
   #:generic-function
   #:type
   #:*discard-documentation-p*
   #:reference
   #:method
   #:find-source
   #:compiler-macro
   #:macro
   #:locate-and-find-source
   #:define-symbol-locative-type
   #:define-definer-for-symbol-locative-type
   #:reader
   #:function
   #:canonical-reference
   #:collect-reachable-objects
   #:locate-and-collect-reachable-objects
   #:locate-and-document
   #:locative-type
   #:class
   #:condition
   #:document-object
   #:locative-args
   #:exportable-locative-type-p
   #:writer
   #:defsection
   #:section
   #:section-title
   #:section-name
   #:section-entries
   #:reference-object
   #:package
   #:define-package
   #:*document-mark-up-signatures*
   #:*document-link-code*
   #:*document-link-sections*
   #:*document-min-link-hash-length*
   #:*document-uppercase-is-code*
   #:*document-max-numbering-level*
   #:*document-max-table-of-contents-level*
   #:*document-text-navigation*
   #:*document-fancy-html-navigation*
   #:*document-normalize-packages*))
