;;;; This file was generated by
;;;;
;;;;   (autoload:record-loaddefs "mgl-pax")
;;;;
;;;; Do not edit.

(in-package :cl)

(autoload::ensure-package-names "mgl-pax" '("pax"))

(autoload::set-package-documentation "mgl-pax" "See MGL-PAX::@PAX-MANUAL.")

(autoload::use-package*
 '("autoload" "common-lisp" "dref" "dref-ext" "editor-hints.named-readtables"
   "pythonic-string-reader")
 "mgl-pax")

(autoload::import*
 '(("alexandria" . "compose") ("alexandria" . "curry")
   ("alexandria" . "ends-with") ("alexandria" . "ends-with-subseq")
   ("alexandria" . "featurep") ("alexandria" . "first-elt")
   ("alexandria" . "hash-table-keys") ("alexandria" . "hash-table-plist")
   ("alexandria" . "if-let") ("alexandria" . "last-elt")
   ("alexandria" . "nth-value-or") ("alexandria" . "once-only")
   ("alexandria" . "plist-hash-table") ("alexandria" . "rcurry")
   ("alexandria" . "read-file-into-string")
   ("alexandria" . "read-stream-content-into-string")
   ("alexandria" . "starts-with") ("alexandria" . "starts-with-subseq")
   ("alexandria" . "when-let") ("alexandria" . "with-gensyms")
   ("common-lisp" . "go"))
 "mgl-pax")

(autoload::export*
 '("*browse-html-style*" "*discard-documentation-p*" "*document-base-url*"
   "*document-downcase-uppercase-code*" "*document-fancy-html-navigation*"
   "*document-html-bottom-blocks-of-links*" "*document-html-charset*"
   "*document-html-default-style*" "*document-html-head*"
   "*document-html-lang*"
   "*document-html-max-navigation-table-of-contents-level*"
   "*document-html-sidebar*" "*document-html-top-blocks-of-links*"
   "*document-hyperspec-root*" "*document-link-code*"
   "*document-link-sections*" "*document-link-to-hyperspec*"
   "*document-mark-up-signatures*" "*document-max-numbering-level*"
   "*document-max-table-of-contents-level*" "*document-min-link-hash-length*"
   "*document-normalize-packages*" "*document-pandoc-pdf-header-includes*"
   "*document-pandoc-pdf-metadata-block*" "*document-pandoc-pdf-options*"
   "*document-pandoc-program*" "*document-text-navigation*"
   "*document-tight*" "*document-uppercase-is-code*"
   "*document-url-versions*" "*format*" "*transcribe-check-consistency*"
   "*transcribe-syntaxes*" "accessor" "argument" "clhs" "constant"
   "define-glossary-term" "define-package" "defsection" "delete-comments"
   "delete-trailing-whitespace" "dislocated" "docstring" "doctitle"
   "doctitle*" "document" "document-docstring" "document-object*"
   "documenting-definition" "ensure-web-server" "escape-markdown"
   "exportable-locative-type-p" "exportable-reference-p" "glossary-term"
   "glossary-term-name" "glossary-term-title" "glossary-term-url" "go"
   "include" "install-pax-elisp" "locative" "macro" "make-git-source-uri-fn"
   "make-github-source-uri-fn" "note" "output-label" "output-reflink"
   "prin1-to-markdown" "reader" "register-doc-in-pax-world" "section"
   "section-entries" "section-link-title-to" "section-name" "section-package"
   "section-readtable" "section-title" "squeeze-whitespace"
   "standard-transcribe-dynenv" "structure-accessor" "symbol-macro"
   "transcribe" "transcription-consistency-error" "transcription-error"
   "transcription-output-consistency-error"
   "transcription-values-consistency-error" "unknown" "unresolvable-reflink"
   "update-asdf-system-html-docs" "update-asdf-system-readmes"
   "update-pax-world" "with-dislocated-names" "with-heading" "writer")
 "mgl-pax")

(autoload::foreshadow-defvar mgl-pax:*browse-html-style* :init :charter
                             :docstring
                             "The HTML style to use for browsing live documentation. Affects only
  non-w3m browsers. See *DOCUMENT-HTML-DEFAULT-STYLE* for the possible
  values.

  If you change this variable, you may need to do a hard refresh in
  the browser (often `C-<f5>`).")

(autoload::foreshadow-defvar mgl-pax:*document-base-url* :init nil :docstring
                             "When *DOCUMENT-BASE-URL* is non-NIL, this is prepended to all
  Markdown relative URLs. It must be a valid URL without query or
  fragment parts (that is, _http://lisp.org/doc/_ but not
  _http://lisp.org/doc?a=1_ or _http://lisp.org/doc#fragment_). Note
  that intra-page links using only URL fragments (e.g. and explicit
  HTML links (e.g. `<a href=\"...\">`) in Markdown are not
  affected.")

(autoload::foreshadow-defvar mgl-pax:*document-downcase-uppercase-code* :init
                             nil :docstring
                             "If true, then all @MARKDOWN/INLINE-CODE (e.g. \\`code\\`, _which
  renders as_ `\\code`) – including @CODIFICATION – which has no
  lowercase characters is downcased in the output. Characters of
  literal strings in the code may be of any case. If this variable is
  :ONLY-IN-MARKUP and the output format does not support markup (e.g.
  it's :PLAIN), then no downcasing is performed. For example,

      `(PRINT \"Hello\")`

  is downcased to

      `(print \"Hello\")`

  because it only contains uppercase characters outside the string.
  However,

      `MiXed \"RESULTS\"`

  is not altered because it has lowercase characters.

  If the first two characters are backslashes, then no downcasing is
  performed, in addition to @ESCAPING-AUTOLINKING. Use this to mark
  inline code that's not Lisp.

      Press `\\\\M-.` in Emacs.")

(autoload::foreshadow-defvar mgl-pax:*document-fancy-html-navigation* :init t
                             :docstring
                             "If true and the output format is HTML, then headings get a
  navigation component that consists of links to the previous, parent,
  next section, a self-link, and a link to the definition in the
  source code if available (see :SOURCE-URI-FN in DOCUMENT). This
  component is normally hidden, it is visible only when the mouse is
  over the heading. Has no effect if *DOCUMENT-LINK-SECTIONS* is
  false.")

(autoload::foreshadow-defvar mgl-pax:*document-html-bottom-blocks-of-links*
                             :init nil :docstring
                             "Like *DOCUMENT-HTML-TOP-BLOCKS-OF-LINKS*, only it is displayed
  below the table of contents.")

(autoload::foreshadow-defvar mgl-pax:*document-html-charset* :init "UTF-8"
                             :docstring
                             "The value for `charset` attribute of the `<meta http-equiv='Content-Type'
  content='text/html'>` element in the generated HTML.")

(autoload::foreshadow-defvar mgl-pax:*document-html-default-style* :init
                             :default :docstring
                             "The HTML style to use. It's either STYLE is either :DEFAULT or
  :CHARTER. The :DEFAULT CSS stylesheet relies on the default
  fonts (sans-serif, serif, monospace), while :CHARTER bundles some
  fonts for a more controlled look.

  The value of this variable affects the default style of
  UPDATE-ASDF-SYSTEM-HTML-DOCS.")

(autoload::foreshadow-defvar mgl-pax:*document-html-head* :init nil
                             :docstring
                             "Stuff to be included in the `<head>` of the generated HTML.

  - If NIL, nothing is included.

  - If a STRING, then it is written to the HTML output as is without
    any escaping.

  - If a function designator, then it is called with a single
    argument, the HTML stream, where it must write the output.")

(autoload::foreshadow-defvar mgl-pax:*document-html-lang* :init "en"
                             :docstring
                             "The value for the `html` element's `xml:lang` and `lang`
  attributes in the generated HTML.")

(autoload::foreshadow-defvar
 mgl-pax:*document-html-max-navigation-table-of-contents-level* :init nil
 :docstring "NIL or a non-negative integer. If non-NIL, it overrides
  *DOCUMENT-MAX-NUMBERING-LEVEL* in the dynamic HTML table of contents
  on the left of the page.")

(autoload::foreshadow-defvar mgl-pax:*document-html-sidebar* :init nil
                             :docstring
                             "Stuff to be included in the HTML sidebar.

  - If NIL, a default sidebar is generated, with
    *DOCUMENT-HTML-TOP-BLOCKS-OF-LINKS*, followed by the dynamic table
    of contents, and *DOCUMENT-HTML-BOTTOM-BLOCKS-OF-LINKS*.

  - If a STRING, then it is written to the HTML output as is without
    any escaping.

  - If a function designator, then it is called with a single
    argument, the HTML stream, where it must write the output.")

(autoload::foreshadow-defvar mgl-pax:*document-html-top-blocks-of-links*
                             :init nil :docstring
                             "A list of blocks of links to be displayed on the sidebar on the left,
  above the table of contents. A block is of the form `(&KEY TITLE ID
  LINKS)`, where TITLE will be displayed at the top of the block in a
  HTML `DIV` with `ID` followed by the links. LINKS is a list of `(URI
  LABEL)` elements, where `URI` maybe a string or an object being
  DOCUMENTed or a REFERENCE thereof.")

(autoload::foreshadow-defvar mgl-pax:*document-hyperspec-root* :init
                             "http://www.lispworks.com/documentation/HyperSpec/"
                             :docstring "A \\URL of the Common Lisp HyperSpec.
  The default value is the canonical location. When [invoked from
  Emacs][ @browsing-live-documentation], the Elisp variable
  `common-lisp-hyperspec-root` is in effect.")

(autoload::foreshadow-defvar mgl-pax:*document-link-code* :init t :docstring
                             "Whether definitions of things other than [SECTION][class]s
  are allowed to be @LINKABLE.")

(autoload::foreshadow-defvar mgl-pax:*document-link-sections* :init t
                             :docstring
                             "When true, HTML anchors and PDF destinations are generated before
  the headings (e.g. of sections), which allows the table of contents
  to contain links and also code-like references to sections (like
  `@FOO-MANUAL`) to be translated to links with the
  [TITLE][DEFSECTION] being the link text.")

(autoload::foreshadow-defvar mgl-pax:*document-link-to-hyperspec* :init t
                             :docstring
                             "If true, consider definitions found in the Common Lisp HyperSpec
  for linking. For example,

  - `\\PRINT` _renders as_ PRINT.

  In offline documentation, this would be a link to the hyperspec
  unless `#'PRINT` in the running Lisp is @DOCUMENTABLE.

  When @BROWSING-LIVE-DOCUMENTATION, everything is @LINKABLE, so the
  generated link will go to a disambiguation page that lists the
  definition in the Lisp and in the HyperSpec.

  Locatives work as expected (see *DOCUMENT-LINK-CODE*): `\\FIND-IF`
  links to FIND-IF, `\\FUNCTION` links to FUNCTION, and
  `[FUNCTION][type]` links to [FUNCTION][type].

  @UNSPECIFIC-AUTOLINKing to T and NIL is suppressed. If desired, use
  @REFLINKs such as `[T][]` (that links to [T][]) or
  `[T][constant]` (that links to [T][constant]).

  Note that linking explicitly with the CLHS locative is not subject
  to the value of this variable.")

(autoload::foreshadow-defvar mgl-pax:*document-mark-up-signatures* :init t
                             :docstring
                             "When true, some things such as function names and arglists are
  rendered as bold and italic. In @HTML-OUTPUT and @PDF-OUTPUT,
  locative types become links to sources (if :SOURCE-URI-FN is
  provided, see @PAGES), and the symbol becomes a self-link for your
  permalinking pleasure.

  For example, a reference is rendered in Markdown roughly as:

      - [function] foo x y

  With this option on, the above becomes:

      - [function] **foo** *x y*

  Also, in HTML `**foo**` will be a link to that very entry and
  `[function]` may turn into a link to sources.")

(autoload::foreshadow-defvar mgl-pax:*document-max-numbering-level* :init 3
                             :docstring
                             "A non-negative integer. In their hierarchy, sections on levels less
  than this value get numbered in the format of `3.1.2`. Setting it to
  0 turns numbering off.")

(autoload::foreshadow-defvar mgl-pax:*document-max-table-of-contents-level*
                             :init 3 :docstring
                             "An integer that determines the depth of the table of contents.

  - If negative, then no table of contents is generated.

  - If non-negative, and there are multiple top-level sections on a
    page, then they are listed at the top of the page.

  - If positive, then for each top-level section a table of contents
    is printed after its heading, which includes a nested tree of
    section titles whose depth is limited by this value.

  If *DOCUMENT-LINK-SECTIONS* is true, then the tables will link to
  the sections.")

(autoload::foreshadow-defvar mgl-pax:*document-min-link-hash-length* :init 4
                             :docstring
                             "Recall that @MARKDOWN/REFLINKs (like `[label][id]`) are used for
  @LINKING. It is desirable to have ids that are short to maintain
  legibility of the generated Markdown, but also stable to reduce the
  spurious diffs in the generated documentation, which can be a pain
  in a version control system.

  Clearly, there is a tradeoff here. This variable controls how many
  characters of the MD5 sum of the full link id (the reference as a
  string) are retained. If collisions are found due to the low number
  of characters, then the length of the hash of the colliding
  reference is increased.

  This variable has no effect on the HTML generated from Markdown, but
  it can make Markdown output more readable.")

(autoload::foreshadow-defvar mgl-pax:*document-normalize-packages* :init t
                             :docstring
                             "Whether to print `[in package <package-name>]` in the documentation
  when the package changes.")

(autoload::foreshadow-defvar mgl-pax:*document-pandoc-pdf-header-includes*
                             :docstring
                             "LaTeX code (a string) to include in the preamble via
  [`header-includes`](https://pandoc.org/MANUAL.html#layout).

  The default includes have no configuration knobs. Look at the value
  to see how to customize it.")

(autoload::foreshadow-defvar mgl-pax:*document-pandoc-pdf-metadata-block*
                             :init "" :docstring
                             "A @PANDOC-YAML-METADATA-BLOCK as a string.

  Concatenate to this string to customize it.")

(autoload::foreshadow-defvar mgl-pax:*document-pandoc-pdf-options* :docstring
                             "The command-line options to invoke *DOCUMENT-PANDOC-PROGRAM* with.
  For ease of manipulation, related options are grouped into sublists,
  but the entire nested list is flattened to get the list of options
  to pass to Pandoc. If `--verbose` is specified, then in addition to
  Pandoc logging LaTeX sources, PAX will log to *ERROR-OUTPUT* the
  Markdown that it converts to PDF via LaTeX. The Markdown includes
  *DOCUMENT-PANDOC-PDF-HEADER-INCLUDES* and
  *DOCUMENT-PANDOC-PDF-METADATA-BLOCK*.")

(autoload::foreshadow-defvar mgl-pax:*document-pandoc-program* :init "pandoc"
                             :docstring
                             "The name of the Pandoc binary. It need not be an absolute pathname
  as `\\\\PATH` is searched.")

(autoload::foreshadow-defvar mgl-pax:*document-text-navigation* :init nil
                             :docstring
                             "If true, then before each heading a line is printed with links to
  the previous, parent and next section. Needs
  *DOCUMENT-LINK-SECTIONS* to be on to work.")

(autoload::foreshadow-defvar mgl-pax:*document-tight* :init nil :docstring
                             "If NIL, then DOCUMENT adds a newline between consecutive
  [atomic][clhs] documentables on the same [page][@pages].")

(autoload::foreshadow-defvar mgl-pax:*document-uppercase-is-code* :init t
                             :docstring
                             "When true, @INTERESTING @NAMEs extracted from @CODIFIABLE @WORDs
  marked up as code with backticks. For example, this docstring

      \"T PRINT CLASSes SECTION *PACKAGE* MGL-PAX ASDF
      CaMeL Capital\"

  is equivalent to this:

      \"`T` `PRINT` `CLASS`es `SECTION` `*PACKAGE*` `MGL-PAX` `ASDF`
      CaMel Capital\"

  and renders as

  `T` `PRINT` `CLASS`es `SECTION` `MGL-PAX` `ASDF` CaMel Capital

  where the links are added due to *DOCUMENT-LINK-CODE*.

  [handle-codification-escapes function][docstring]")

(autoload::foreshadow-defvar mgl-pax:*document-url-versions* :init '(2 1)
                             :docstring
                             "A list of versions of PAX \\URL formats to support in the
  generated documentation. The first in the list is used to generate
  links.

  PAX emits HTML anchors before the documentation of SECTIONs
  (see @LINKING-TO-SECTIONS) and other things (see @LINKING). For the
  function `FOO`, in the current version (version 2), the anchor is
  `<a id=\"MGL-PAX:FOO%20FUNCTION\">`, and its \\URL will end
  with `\\\\#MGL-PAX:FOO%20FUNCTION`.

  _Note that to make the \\URL independent of whether a symbol is
  [internal or external][find-symbol] to their SYMBOL-PACKAGE, single
  colon is printed where a double colon would be expected. Package and
  symbol names are both printed verbatim except for escaping colons
  and spaces with a backslash. For exported symbols with no funny
  characters, this coincides with how PRIN1 would print the symbol,
  while having the benefit of making the \\URL independent of the Lisp
  printer's escaping strategy and producing human-readable output for
  mixed-case symbols. No such promises are made for non-ASCII
  characters, and their \\URLs may change in future versions. Locatives
  are printed with PRIN1._

  Version 1 is based on the more strict HTML4 standard and the id of
  `FOO` is `\"x-28MGL-PAX-3A-3AFOO-20FUNCTION-29\"`. This is supported
  by GitHub-flavoured Markdown. Version 2 has minimal clutter and is
  obviously preferred. However, in order not to break external links,
  by default, both anchors are generated.

  Let's understand the generated Markdown.

  ```
  (defun foo (x))

  (document #'foo :format :markdown)
  => (\"<a id=\\\"x-28MGL-PAX-3AFOO-20FUNCTION-29\\\"></a>
  <a id=\\\"MGL-PAX:FOO%20FUNCTION\\\"></a>

  - [function] **FOO** *X*
  \")

  (let ((*document-url-versions* '(1)))
    (document #'foo :format :markdown))
  => (\"<a id=\\\"x-28MGL-PAX-3AFOO-20FUNCTION-29\\\"></a>

  - [function] **FOO** *X*
  \")
  ```
  ")

(autoload::foreshadow-defvar mgl-pax:*transcribe-check-consistency* :init nil
                             :docstring
                             "The default value of TRANSCRIBE's CHECK-CONSISTENCY argument.")

(autoload::foreshadow-defvar mgl-pax:*transcribe-syntaxes* :init
                             '((:default (:output "..")
                                (:no-value "=> ; No value") (:readable "=>")
                                (:unreadable "==>")
                                (:unreadable-continuation "-->"))
                               (:commented-1 (:output ";..")
                                (:no-value ";=> ; No value")
                                (:readable ";=>")
                                (:readable-continuation ";->")
                                (:unreadable ";==>")
                                (:unreadable-continuation ";-->"))
                               (:commented-2 (:output ";;..")
                                (:no-value ";;=> ; No value")
                                (:readable ";;=>")
                                (:readable-continuation ";;->")
                                (:unreadable ";;==>")
                                (:unreadable-continuation ";;-->")))
                             :docstring
                             "The default syntaxes used by TRANSCRIBE for reading and writing
  lines containing output and values of an evaluated form.

  A syntax is a list of of the form `(SYNTAX-ID &REST PREFIXES)` where
  `PREFIXES` is a list of `(PREFIX-ID PREFIX-STRING)` elements. For
  example the syntax :COMMENTED-1 looks like this:

  ```
  (:commented-1
   (:output \";..\")
   (:no-value \";=>  No value\")
   (:readable \";=>\")
   (:readable-continuation \";->\")
   (:unreadable \";==>\")
   (:unreadable-continuation \";-->\"))
  ```

  All of the above prefixes must be defined for every syntax except
  for :READABLE-CONTINUATION. If that's missing (as in the :DEFAULT
  syntax), then the following value is read with READ and printed with
  PRIN1 (hence no need to mark up the following lines).

  When writing, an extra space is added automatically if the line to
  be prefixed is not empty. Similarly, the first space following the
  prefix is discarded when reading.

  See TRANSCRIBE for how the actual syntax to be used is selected.")

(autoload:autoload mgl-pax::call-with-heading "mgl-pax/document" :arglist
                   "(stream dref:dref mgl-pax::link-title-to mgl-pax::fn)")

(autoload:autoload mgl-pax::downcasingp "mgl-pax/document" :arglist "nil")

(autoload:autoload mgl-pax::ensure-transcribe-loaded "mgl-pax/transcribe"
                   :arglist "nil")

(autoload:autoload mgl-pax::escape-tex "mgl-pax/document" :arglist "(string)"
                   :docstring
                   "Construct a new string from STRING by adding a backslash before
  special TeX characters

      &%$#_{}~^\\")

(autoload:autoload mgl-pax::print-dref-bullet "mgl-pax/document" :arglist
                   "(dref:dref stream)")

(autoload:autoload mgl-pax:delete-comments "mgl-pax/transcribe" :arglist
                   "(string &key (mgl-pax::pattern \";\"))" :docstring
                   "For each line in STRING delete the rest of the line after and
  including the first occurrence of PATTERN. On changed lines, delete
  trailing whitespace too. This function does not parse STRING as Lisp
  forms, hence all occurrences of PATTERN (even those seemingly in
  string literals) are recognized as comments.

  Let's define a comparison function:

  ```cl-transcript (:dynenv pax-std-env)
  (defun string=/no-comments (string1 string2)
    (string= (delete-comments string1) (delete-comments string2)))
  ```

  And use it to check consistency of output:

      ```cl-transcript (:check-consistency ((:output string=/no-comments)))
      (format t \"hello~%world\")
      .. hello     ; This is the first line.
      .. world     ; This is the second line.
      ```

  Just to make sure the above example works, here it is without being
  quoted.

  ```cl-transcript (:check-consistency ((:output string=/no-comments)))
  (format t \"hello~%world\")
  .. hello     ; This is the first line.
  .. world     ; This is the second line.
  ```")

(autoload:autoload mgl-pax:delete-trailing-whitespace "mgl-pax/transcribe"
                   :arglist "(string)" :docstring
                   "Delete whitespace characters after the last non-whitespace
  character in each line in STRING.")

(autoload:autoload mgl-pax:doctitle "mgl-pax/document" :arglist
                   "(mgl-pax::object)" :docstring
                   "Return the @TITLE of OBJECT if it has one or NIL. For
  @CODIFICATION, the title is interpreted in the package returned by
  DOCSTRING. DOCTITLE can be extended via DOCTITLE*.")

(autoload:autoload mgl-pax:document "mgl-pax/document" :arglist
                   "(mgl-pax::documentable &key (stream t) mgl-pax::pages (format :plain))"
                   :docstring
                   "Write DOCUMENTABLE in FORMAT to STREAM diverting some output to PAGES.
  FORMAT is one of [:PLAIN][@plain-output],
  [:MARKDOWN][@markdown-output], [:HTML][@html-output] and
  [:PDF][@pdf-output] or [NIL][@dummy-output]. STREAM may be a
  [STREAM][type] object, T or NIL as with [CL:FORMAT][].

  To look up the documentation of the DOCUMENT function itself:

      (document #'document)

  The same with fancy markup:

      (document #'document :format :markdown)

  To document a SECTION:

      (document pax::@pax-manual)

  To generate the documentation for separate libraries with automatic
  cross-links:

      (document (list pax::@pax-manual dref::@dref-manual) :format :markdown)

  See @DOCUMENTATION-UTILITIES for more.

  Definitions that do not define a first-class object are supported
  via [DRef][dref::@dref-manual]:

      (document (dref:locate 'foo 'type))

  There are quite a few special variables that affect how output is
  generated, see @CODIFICATION, @LINKING-TO-THE-HYPERSPEC,
  @LINKING-TO-SECTIONS, @LINK-FORMAT and @OUTPUT-FORMATS.

  For the details, see the following sections, starting with
  @DOCUMENTABLE. Also see @EXTENSION-API and DOCUMENT-OBJECT*.")

(autoload:autoload mgl-pax:document-docstring "mgl-pax/document" :arglist
                   "(mgl-pax:docstring stream &key (mgl-pax::indentation \"    \") mgl-pax::exclude-first-line-p (mgl-pax::paragraphp t))"
                   :docstring
                   "Write DOCSTRING to STREAM, [sanitizing the Markdown]
  [@markdown-in-docstrings] from it, performing @CODIFICATION and
  @LINKING, finally prefixing each line with INDENTATION. The prefix
  is not added to the first line if EXCLUDE-FIRST-LINE-P. If
  PARAGRAPHP, then add a newline before and after the output.")

(autoload:autoload mgl-pax:ensure-web-server "mgl-pax/web" :arglist
                   "(&key mgl-pax::port mgl-pax::hyperspec-root)" :docstring
                   "Start or update a web server on PORT of localhost for
  @BROWSING-LIVE-DOCUMENTATION. Returns the base URL of the
  server (e.g. `http://localhost:32790`), which goes to the
  @PAX-LIVE-HOME-PAGE. If the web server is running
  already `(ENSURE-WEB-SERVER)` simply returns its base URL.

  Note that even when using Emacs but @BROWSING-WITH-OTHER-BROWSERS,
  the web server is started automatically. When @BROWSING-WITH-W3M, no
  web server is involved at all. Calling this function explicitly is
  only needed if the Emacs integration is not used, or to override
  PORT and HYPERSPEC-ROOT.

  - If PORT is NIL or 0, then the server will use any free port.

  - If there is a server already running and PORT is not NIL or 0,
    then the server is restarted on PORT.

  - If HYPERSPEC-ROOT is NIL, the HyperSpec pages will be served from
    any previously provided HYPERSPEC-ROOT or, failing that, from
    *DOCUMENT-HYPERSPEC-ROOT*.

  - If HYPERSPEC-ROOT is non-NIL, then pages in the HyperSpec will be
    served from HYPERSPEC-ROOT. The following command changes the root
    without affecting the server in any other way:

          (ensure-web-server :hyperspec-root \"/usr/share/doc/hyperspec/\")
  ")

(autoload:autoload mgl-pax:escape-markdown "mgl-pax/document" :arglist
                   "(string &key (mgl-pax::escape-inline t) (mgl-pax::escape-mathjax t) (mgl-pax::escape-html t) (mgl-pax::escape-block t))"
                   :docstring "Backslash escape Markdown constructs in STRING.

  - If ESCAPE-INLINE, then escape the following characters:

          *_`[]\\
  - If ESCAPE-MATHJAX, then escape `$` characters.

  - If ESCAPE-HTML, then escape the following characters:

          <&

  - If ESCAPE-BLOCK, then escape whatever is necessary to avoid
    starting a new Markdown block (e.g. a paragraph, heading, etc).")

(autoload:autoload mgl-pax:prin1-to-markdown "mgl-pax/document" :arglist
                   "(mgl-pax::object &key (mgl-pax::escape-inline t) (mgl-pax::escape-mathjax t) (mgl-pax::escape-html t) (mgl-pax::escape-block t))"
                   :docstring
                   "Like PRIN1-TO-STRING, but bind *PRINT-CASE* depending on
  *DOCUMENT-DOWNCASE-UPPERCASE-CODE* and *FORMAT*, and
  ESCAPE-MARKDOWN.")

(autoload:autoload mgl-pax:squeeze-whitespace "mgl-pax/transcribe" :arglist
                   "(string)" :docstring
                   "Replace consecutive whitespace characters with a single space in
  STRING and trim whitespace from the right. This is useful to undo
  the effects of pretty printing when building comparison functions
  for TRANSCRIBE.")

(autoload:autoload mgl-pax:standard-transcribe-dynenv "mgl-pax/transcribe"
                   :arglist "(mgl-pax::fn)" :docstring
                   "Bind printer and reader variables to standard values and call FN.

  The bindings are the same as with WITH-STANDARD-IO-SYNTAX, but

  - *PACKAGE* and *READTABLE* are unaffected (because both DOCUMENT
    and Emacs set these up);

  - *PRINT-READABLY* is NIL, *PRINT-PRETTY* is T, *PRINT-CIRCLE* is T
    and *PRINT-RIGHT-MARGIN* is 72.

  This function is the default for the :DYNENV argument of
  `cl-transcript`. A function that overrides the default may want to
  call STANDARD-TRANSCRIBE-DYNENV with a lambda that establishes more
  bindings.")

(autoload:autoload mgl-pax:transcribe "mgl-pax/transcribe" :arglist
                   "(mgl-pax::input mgl-pax::output &key mgl-pax::update-only (mgl-pax::include-no-output mgl-pax::update-only) (mgl-pax::include-no-value mgl-pax::update-only) (mgl-pax::echo t) (mgl-pax::check-consistency mgl-pax:*transcribe-check-consistency*) mgl-pax::default-syntax (mgl-pax::input-syntaxes mgl-pax:*transcribe-syntaxes*) (mgl-pax::output-syntaxes mgl-pax:*transcribe-syntaxes*))"
                   :docstring
                   "Read forms from INPUT and write them (iff ECHO) to OUTPUT
  followed by any output and return values produced by calling EVAL on
  the form.

  INPUT can be a stream or a string, while OUTPUT can be a stream or
  NIL, in which case output goes into a string.
  @@TRANSCRIBE-1ST-RETURN-VALUE @@TRANSCRIBE-2ND-RETURN-VALUE

  Go up to @TRANSCRIBING-WITH-EMACS for nice examples. A more
  mind-bending one is this:

  ```cl-transcript
  (transcribe \"(princ 42) \" nil)
  => \"(princ 42)
  .. 42
  => 42
  \"
  => T
  ```

  However, the above may be a bit confusing since this documentation
  uses TRANSCRIBE markup syntax in this very example, so let's do it
  differently. If we have a file with these contents:

  ```
  (values (princ 42) (list 1 2))
  ```

  it is transcribed to:

  ```
  (values (princ 42) (list 1 2))
  .. 42
  => 42
  => (1 2)
  ```

  Output to all standard streams is captured and printed with
  the :OUTPUT prefix (`\"..\"`). The return values above are printed
  with the :READABLE prefix (`\"=>\"`). Note how these prefixes are
  always printed on a new line to facilitate parsing.

  **Updating**

  TRANSCRIBE is able to parse its own output. If we transcribe the
  previous output above, we get it back exactly. However, if we remove
  all output markers, leave only a placeholder value marker and
  pass :UPDATE-ONLY T with source:

  ```
  (values (princ 42) (list 1 2))
  =>
  ```

  we get this:

  ```
  (values (princ 42) (list 1 2))
  => 42
  => (1 2)
  ```

  With UPDATE-ONLY, the printed output of a form is transcribed only
  if there were output markers in the source. Similarly, with
  UPDATE-ONLY, return values are transcribed only if there were value
  markers in the source.

  **No Output/Values**

  If the form produces no output or returns no values, then whether or
  not output and values are transcribed is controlled by
  INCLUDE-NO-OUTPUT and INCLUDE-NO-VALUE, respectively. By default,
  neither is on so:

  ```
  (values)
  ..
  =>
  ```

  is transcribed to

  ```
  (values)
  ```

  With UPDATE-ONLY true, we probably wouldn't like to lose those
  markers since they were put there for a reason. Hence, with
  UPDATE-ONLY, INCLUDE-NO-OUTPUT and INCLUDE-NO-VALUE default to true.
  So, with UPDATE-ONLY the above example is transcribed to:

  ```
  (values)
  ..
  => ; No value
  ```

  where the last line is the :NO-VALUE prefix.

  **Consistency Checks**

  If CHECK-CONSISTENCY is true, then TRANSCRIBE signals a continuable
  TRANSCRIPTION-OUTPUT-CONSISTENCY-ERROR whenever a form's output as a
  string is different from what was in INPUT, provided that INPUT
  contained the output. Similarly, for values, a continuable
  TRANSCRIPTION-VALUES-CONSISTENCY-ERROR is signalled if a value read
  from the source does not print as the as the value returned by EVAL.
  This allows readable values to be hand-indented without failing
  consistency checks:

  ```
  (list 1 2)
  => ;; This is commented, too.
     (1
        ;; Funny indent.
        2)
  ```

  See @TRANSCRIPT-CONSISTENCY-CHECKING for the full picture.

  **Unreadable Values**

  The above scheme involves READ, so consistency of unreadable values
  cannot be treated the same. In fact, unreadable values must even be
  printed differently for transcribe to be able to read them back:

  ```
  (defclass some-class () ())

  (defmethod print-object ((obj some-class) stream)
    (print-unreadable-object (obj stream :type t)
      (format stream \"~%~%end\")))

  (make-instance 'some-class)
  ==> #<SOME-CLASS 
  -->
  --> end>
  ```

  where `\"==>\"` is the :UNREADABLE prefix and `\"-->\"` is the
  :UNREADABLE-CONTINUATION prefix. As with outputs, a consistency
  check between an unreadable value from the source and the value from
  EVAL is performed with STRING= by default. That is, the value from
  EVAL is printed to a string and compared to the source value. Hence,
  any change to unreadable values will break consistency checks. This
  is most troublesome with instances of classes with the default
  PRINT-OBJECT method printing the memory address. See
  @TRANSCRIPT-FINER-GRAINED-CONSISTENCY-CHECKS.

  **Errors**

  If an ERROR condition is signalled, the error is printed to the
  output and no values are returned.

  ```cl-transcript
  (progn
    (print \"hello\")
    (error \"no greeting\"))
  ..
  .. \"hello\" 
  .. debugger invoked on SIMPLE-ERROR:
  ..   no greeting
  ```

  To keep the textual representation somewhat likely to be portable,
  the printing is done with `(FORMAT T \"#<~S ~S>\" (TYPE-OF
  ERROR) (PRINC-TO-STRING ERROR))`. SIMPLE-CONDITIONs are formatted to
  strings with SIMPLE-CONDITION-FORMAT-CONTROL and
  SIMPLE-CONDITION-FORMAT-ARGUMENTS.

  **Syntaxes**

  Finally, a transcript may employ different syntaxes for the output
  and values of different forms. When INPUT is read, the syntax for
  each form is determined by trying to match all prefixes from all
  syntaxes in INPUT-SYNTAXES against a line. If there are no output or
  values for a form in INPUT, then the syntax remains undetermined.

  When OUTPUT is written, the prefixes to be used are looked up in
  DEFAULT-SYNTAX of OUTPUT-SYNTAXES if DEFAULT-SYNTAX is not NIL. If
  DEFAULT-SYNTAX is NIL, then the syntax used by the same form in the
  INPUT is used or (if that could not be determined) the syntax of the
  previous form. If there was no previous form, then the first syntax
  if OUTPUT-SYNTAXES is used.

  To produce a transcript that's executable Lisp code,
  use :DEFAULT-SYNTAX :COMMENTED-1:

  ```
  (make-instance 'some-class)
  ;==> #<SOME-CLASS
  ;-->
  ;--> end>

  (list 1 2)
  ;=> (1
  ;->    2)
  ```

  To translate the above to uncommented syntax, use :DEFAULT-SYNTAX
  :DEFAULT. If DEFAULT-SYNTAX is NIL (the default), the same syntax
  will be used in the output as in the input as much as possible.")

(autoload:autoload mgl-pax:update-asdf-system-html-docs "mgl-pax/document"
                   :arglist
                   "(mgl-pax::sections mgl-pax::asdf-system &key mgl-pax::pages (mgl-pax::target-dir (asdf/system:system-relative-pathname mgl-pax::asdf-system \"doc/\")) (mgl-pax::update-css-p t) (mgl-pax::style mgl-pax:*document-html-default-style*))"
                   :docstring
                   "Generate pretty HTML documentation for a single ASDF system,
  possibly linking to GitHub. If UPDATE-CSS-P, copy the STYLE files to
  TARGET-DIR (see *DOCUMENT-HTML-DEFAULT-STYLE*).

  Example usage:

  ```
  (update-asdf-system-html-docs @pax-manual :mgl-pax)
  ```

  The same, linking to the sources on GitHub:

  ```
  (update-asdf-system-html-docs
    @pax-manual :mgl-pax
    :pages
    `((:objects (,mgl-pax::@pax-manual)
       :source-uri-fn ,(make-git-source-uri-fn
                        :mgl-pax
                        \"https://github.com/melisgl/mgl-pax\"))))
  ```")

(autoload:autoload mgl-pax:update-asdf-system-readmes "mgl-pax/document"
                   :arglist
                   "(mgl-pax::object mgl-pax::asdf-system &key (mgl-pax::url-versions '(1)) (mgl-pax::formats '(:markdown)))"
                   :docstring
                   "Convenience function to generate up to two readme files in the
  directory holding the ASDF-SYSTEM definition. OBJECT is passed on to
  DOCUMENT.

  If :MARKDOWN is in FORMATS, then `README.md` is generated with
  anchors, links, inline code, and other markup added. Not necessarily
  the easiest on the eye in an editor but looks good on GitHub.

  If :PLAIN is in FORMATS, then `\\\\README` is generated, which is
  optimized for reading in text format. It has less cluttery markup
  and no @AUTOLINKing.

  Example usage:

  ```
  (update-asdf-system-readmes @pax-manual :mgl-pax
                              :formats '(:markdown :plain))
  ```

  Note that *DOCUMENT-URL-VERSIONS* is bound to URL-VERSIONS, which
  defaults to using the uglier, version 1 style of URL for the sake of
  GitHub.")

(autoload:autoload mgl-pax:update-pax-world "mgl-pax/document" :arglist
                   "(&key (mgl-pax::docs mgl-pax::*registered-pax-world-docs*) mgl-pax::dir mgl-pax::update-css-p (mgl-pax::style mgl-pax:*document-html-default-style*))"
                   :docstring
                   "Generate HTML documentation for all DOCS. Files are created in
  DIR (`(asdf:system-relative-pathname :mgl-pax \"world/\")` by
  default if DIR is NIL). DOCS is a list of entries of the form (NAME
  SECTIONS PAGE-SPECS). The default for DOCS is all the sections and
  pages registered with REGISTER-DOC-IN-PAX-WORLD.

  In the absence of :HEADER-FN :FOOTER-FN, :OUTPUT, every spec in
  PAGE-SPECS is augmented with HTML headers, footers and output
  location specifications (based on the name of the section).

  If necessary a default page spec is created for every section.")
